### ISSUE TITLE
Is code within chunks self-contained? (i.e., not globally available?)

### ISSUE THREAD

**Issue by aramcb** [STAT545-UBC/Discussion#320]
If I use the following code, I do not get a plot. It only produces the plot if the plot code is within the chunk. Just want to make sure I understand this. Thanks!

```{r}
#First install package via install.packages("gapminder")
library("gapminder")
```
plot(lifeExp ~ year, gapminder)

**Comment by oganm** [comment]
In normal markdown code chunks are for highlighting and formatting purposes. In Rmarkdown chunks marked as R code will be evaluated. Anything that remains outside of a chunk is just text and will not be run. Otherwise you wouldn't be able to comfortably write text to the file

**Comment by samhinshaw** [comment]
To illustrate what Ogan said, if you are creating an R Markdown document, any code you wish to be executed must be within an "R code chunk" with the proper formatting:
\`\`\{r}
\<code to be executed\>
\`\`\`

Any other type of formatting will be exclusively stylistic, for example:
\`\`\`
\<text that you want to be displayed as code, but not executed\>
\`\`\`

**Comment by RosieRedfield** [comment]
So the ' ```    ``` ' tells markdown to display the included text as code, and the ' {r} ' tells markdown to also execute it as RE code?

**Comment by RosieRedfield** [comment]
So the '```    ``` ' tells markdown to display the included text as code, and the ' {r} ' tells markdown to also execute it as RE code?

And the '<   >' brackets also tell markdown to display the included text as code?

**Comment by oganm** [comment]
![](http://vignette4.wikia.nocookie.net/random-ness/images/9/9f/Darth_vader_no.gif/revision/latest?cb=20120616003315)
<> brackets were meant to indicate a hypothetical code that doesn't exist. They have no function here.

**Comment by jennybc** [comment]
Probably helpful to look at a concrete example.

Mostly restating things from here: <http://stat545.com/block007_first-use-rmarkdown.html>

Make an Rmd using the default document, RStudio > File > New Rmarkdown. Save it as "test.Rmd" or whatever.

Edit the yaml so that you get markdown instead of html or in addition to html. So one of these two ways:

``` yaml
---  
    title: "Something fascinating"  
    author: "Jenny Bryan"  
    date: "`r format(Sys.Date())`"
    output: github_document
--- 
```

``` yaml
---  
    title: "Something fascinating"  
    author: "Jenny Bryan"  
    date: "`r format(Sys.Date())`"
    output:  
      html_document:  
        keep_md: true  
---  
```

Save! Knit it via the knitting ball button.

Open "test.md" and compare it to "test.Rmd". Especially the code chunks. The code has been run and the code + output has been inserted inside triple backticks with an `r` but no curly braces. The `{r}` in Rmd is how an R package called knitr knows to execute the code in those chunks and drop the code + output back in to create the markdown file.

The triple backticks are called  ["fenced code block"](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and are the general way to display code in markdown. By indicating the language, such as R or Ruby or Python, you will usually get nice syntax highlighting, which makes the code easier to read.
