### ISSUE TITLE
Getting table of contents to show up in markdown

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#40]
#### Problem
Today in class, it was pointed out that when producing an HTML document with a table of contents, the corresponding intermediate markdown does not have a toc. The following snippet is an example of what you would *expect* to work.

```
output:  
  html_document:  
    toc: true  
    toc_depth: 3  
    keep_markdown: true
```

Unfortunately, the table of contents option is ignored by the intermediate markdown and is only displayed in the HTML.
> sidenote: one of the developers of Rmardkwon confirmed that this behaviour is correct, though I personally think that it's weird and should be "fixed". You can see his response [here](http://rmarkdown.rstudio.com/html_document_format.html#comment-1625596268)

#### Solution
The solution I could come up with is explicitly specifying in the yaml that both an HTML document **and** a markdown document should be produced, and specifying the `toc` option to both. Something like this:
```
output:
  md_document:
    toc: true
    toc_depth: 3
  html_document:
    toc: true
    toc_depth: 3
```
This seems perhaps less than optimal, but it works.  
However, I learned that **specifying multiple output formats like this is not supported by the RStudio 'knit' button**.  Clicking the knit button will only produce the first output format (in this example, it will only generate a markdown document).  **In order to knit the document into both formats (markdown and HTML), you will have to run the command yourself**: `rmarkdown::render("<file_name>.Rmd", "all")`
(if you want to see the response from one of the Rmarkdown developers about this issue, [it's here](http://rmarkdown.rstudio.com/#comment-1625591810))
